//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Wafii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int com_id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Description { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> rest_id { get; set; }
        public Nullable<int> del_id { get; set; }
        public Nullable<int> cus_id { get; set; }
    }
}
